version: '3'

services:
  api:
    build: .
    container_name: api
    command: ["gunicorn", "app:api", "-b", "0.0.0.0:7000", "--reload", "--timeout",  "100000"]
    volumes:
     - .:/app

    ports:
      - "127.0.0.1:7000:7000"